#
# Copyright Â© 2014 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#

language: java

jdk:
  - oraclejdk7

env:
  global:
    - secure: DHoIe2FobpAM/4ZKZX3acpBN/UPQn1FK+OJG87IuvCJ2xQbXMOimIL5l52/PgEbea9wQC+qxOaXhFkDS0SMq+AWw0Haa+b0xUG+D9SdRsMfipBmhHowKNAxRkVp1DE563cibpUv03DbS+XWL1xWv0xrc+ooPKdzZm2jWwAlW1AI=
    - secure: DIURQkS/L8U3TTXTtmhhDLdNJAfB2NqUMb6+K5EYwFS/C37tNPTl1ip23j/KC4PRboJtFNgVqQFo9ErsYY7xk6md6+JCB6Tl/4CzSvtZ6Z9xVssFPdKA6dOryelG6beckGoxfWxSw4zIcx2aODVIkMLR+/86Y+9XJ6pJbkfeGEo=
    - COOPR_SERVER_HOME=`pwd`
    - COOPR_USE_DUMMY_PROVISIONER=true
addons:
  sauce_connect: true

branches:
  only:
    - develop
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    - /^release\/.*$/

before_install:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

before_script:
  - 'cd coopr-ngui && npm run build'
  - 'npm start > /dev/null &'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then cd ../coopr-server; fi'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then mvn clean package assembly:single -DskipTests; fi'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then java -cp target/*:src/test/resources co.cask.coopr.runtime.ServerMain; fi >/dev/null 2>&1 &'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then java -cp target/*:src/test/resources co.cask.coopr.runtime.MockProvisionerMain; fi >/dev/null 2>&1 &'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then ./coopr-server/config/defaults/load-defaults.sh; fi'
  - 'cd .. && sleep 5' # give server time to start

script:
  - 'cd coopr-ngui'
  - 'node ./node_modules/gulp/bin/gulp.js jshint'
  - 'npm run test-single-run'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then npm run protractor; fi'
  - 'cd ..'
  - 'mvn test'

